disabled_rules:
- control_statement
- identifier_name
- trailing_whitespace
opt_in_rules:
- empty_count
included:
- NetflixClone
excluded:
- Pods
force_cast: warning # implicitly
line_length: 220
file_length:
warning: 500
error: 1200
type_name:
min_length: 4 # only warning
max_length: # warning and error
warning: 40
error: 50
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji)
